[target.x86_64-unknown-linux-gnu]
dockerfile = "./Dockerfile.cross"

[target.i686-unknown-linux-gnu]
dockerfile = "./Dockerfile.cross"

[target.aarch64-unknown-linux-gnu]
dockerfile = "./Dockerfile.cross"

[target.armv7-unknown-linux-gnueabihf]
dockerfile = "./Dockerfile.cross"