name: Rust cross-build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - i686-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          - armv7-unknown-linux-gnueabihf
          - x86_64-pc-windows-gnu
          - i686-pc-windows-gnu
    continue-on-error: true

    steps:
    - uses: actions/checkout@v5

    - name: Dependencies
      run: apt install libglib2.0-dev

    - name: Add Rust target
      run: rustup target add ${{ matrix.target }} || true

    - name: Build release
      run: cargo build --release --target ${{ matrix.target }}

    - name: Upload artifact
      uses: actions/upload-artifact@v5
      with:
        name: shootdpi-${{ matrix.target }}
        path: target/${{ matrix.target }}/release/
